
-- ========================================================
-- Comprehensive Performance Review Data Population
-- Generated by populate_performance_data.py
-- ========================================================

-- STEP 1: Create 100 Employee Profiles
-- (This will create profiles that don't already exist)


INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000001'::uuid,
  'emp1@company.com',
  'Sarah',
  'Johnson',
  'employee',
  'Engineering',
  'Senior Software Engineer',
  'EMP0001',
  'active',
  (now() - interval '189 days')::date,
  now() - interval '619 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000002'::uuid,
  'emp2@company.com',
  'Michael',
  'Chen',
  'employee',
  'Engineering',
  'Software Engineer',
  'EMP0002',
  'active',
  (now() - interval '612 days')::date,
  now() - interval '599 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000003'::uuid,
  'emp3@company.com',
  'Emily',
  'Rodriguez',
  'employee',
  'Product',
  'Product Manager',
  'EMP0003',
  'active',
  (now() - interval '317 days')::date,
  now() - interval '460 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000004'::uuid,
  'emp4@company.com',
  'David',
  'Kim',
  'employee',
  'Sales',
  'Account Executive',
  'EMP0004',
  'active',
  (now() - interval '548 days')::date,
  now() - interval '349 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000005'::uuid,
  'emp5@company.com',
  'Jennifer',
  'Martinez',
  'employee',
  'Marketing',
  'Marketing Manager',
  'EMP0005',
  'active',
  (now() - interval '352 days')::date,
  now() - interval '162 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000006'::uuid,
  'emp6@company.com',
  'James',
  'Anderson',
  'employee',
  'Engineering',
  'DevOps Engineer',
  'EMP0006',
  'active',
  (now() - interval '136 days')::date,
  now() - interval '377 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000007'::uuid,
  'emp7@company.com',
  'Maria',
  'Garcia',
  'employee',
  'Customer Success',
  'Customer Success Manager',
  'EMP0007',
  'active',
  (now() - interval '366 days')::date,
  now() - interval '118 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000008'::uuid,
  'emp8@company.com',
  'Robert',
  'Taylor',
  'employee',
  'Finance',
  'Financial Analyst',
  'EMP0008',
  'active',
  (now() - interval '357 days')::date,
  now() - interval '553 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000009'::uuid,
  'emp9@company.com',
  'Linda',
  'Wilson',
  'employee',
  'HR',
  'HR Business Partner',
  'EMP0009',
  'active',
  (now() - interval '436 days')::date,
  now() - interval '446 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000010'::uuid,
  'emp10@company.com',
  'John',
  'Moore',
  'employee',
  'Engineering',
  'Senior Software Engineer',
  'EMP0010',
  'active',
  (now() - interval '622 days')::date,
  now() - interval '225 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000011'::uuid,
  'emp11@company.com',
  'Patricia',
  'Jackson',
  'employee',
  'Customer Success',
  'Coordinator',
  'EMP0011',
  'active',
  (now() - interval '88 days')::date,
  now() - interval '559 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000012'::uuid,
  'emp12@company.com',
  'Christopher',
  'White',
  'employee',
  'Finance',
  'Director',
  'EMP0012',
  'active',
  (now() - interval '458 days')::date,
  now() - interval '479 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000013'::uuid,
  'emp13@company.com',
  'Barbara',
  'Harris',
  'employee',
  'Finance',
  'Coordinator',
  'EMP0013',
  'active',
  (now() - interval '243 days')::date,
  now() - interval '515 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000014'::uuid,
  'emp14@company.com',
  'Daniel',
  'Martin',
  'employee',
  'Operations',
  'Specialist',
  'EMP0014',
  'active',
  (now() - interval '464 days')::date,
  now() - interval '59 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000015'::uuid,
  'emp15@company.com',
  'Nancy',
  'Thompson',
  'employee',
  'HR',
  'Specialist',
  'EMP0015',
  'active',
  (now() - interval '659 days')::date,
  now() - interval '677 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000016'::uuid,
  'emp16@company.com',
  'Matthew',
  'Garcia',
  'employee',
  'Marketing',
  'Manager',
  'EMP0016',
  'active',
  (now() - interval '268 days')::date,
  now() - interval '171 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000017'::uuid,
  'emp17@company.com',
  'Karen',
  'Martinez',
  'employee',
  'Engineering',
  'Specialist',
  'EMP0017',
  'active',
  (now() - interval '212 days')::date,
  now() - interval '501 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000018'::uuid,
  'emp18@company.com',
  'Joseph',
  'Robinson',
  'employee',
  'Product',
  'Director',
  'EMP0018',
  'active',
  (now() - interval '244 days')::date,
  now() - interval '338 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000019'::uuid,
  'emp19@company.com',
  'Susan',
  'Clark',
  'employee',
  'Engineering',
  'Software Engineer',
  'EMP0019',
  'active',
  (now() - interval '447 days')::date,
  now() - interval '605 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000020'::uuid,
  'emp20@company.com',
  'Thomas',
  'Rodriguez',
  'employee',
  'Finance',
  'Lead',
  'EMP0020',
  'active',
  (now() - interval '295 days')::date,
  now() - interval '726 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000021'::uuid,
  'emp21@company.com',
  'Jessica',
  'Lewis',
  'employee',
  'Engineering',
  'Specialist',
  'EMP0021',
  'active',
  (now() - interval '298 days')::date,
  now() - interval '659 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000022'::uuid,
  'emp22@company.com',
  'Charles',
  'Lee',
  'employee',
  'Product',
  'Manager',
  'EMP0022',
  'active',
  (now() - interval '405 days')::date,
  now() - interval '167 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000023'::uuid,
  'emp23@company.com',
  'Sarah',
  'Walker',
  'employee',
  'Operations',
  'Software Engineer',
  'EMP0023',
  'active',
  (now() - interval '107 days')::date,
  now() - interval '663 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000024'::uuid,
  'emp24@company.com',
  'Jason',
  'Hall',
  'employee',
  'Finance',
  'Lead',
  'EMP0024',
  'active',
  (now() - interval '267 days')::date,
  now() - interval '80 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000025'::uuid,
  'emp25@company.com',
  'Lisa',
  'Allen',
  'employee',
  'Customer Success',
  'Manager',
  'EMP0025',
  'active',
  (now() - interval '234 days')::date,
  now() - interval '97 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000026'::uuid,
  'emp26@company.com',
  'Kevin',
  'Young',
  'employee',
  'Sales',
  'Manager',
  'EMP0026',
  'active',
  (now() - interval '422 days')::date,
  now() - interval '129 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000027'::uuid,
  'emp27@company.com',
  'Michelle',
  'Hernandez',
  'employee',
  'Product',
  'Coordinator',
  'EMP0027',
  'active',
  (now() - interval '353 days')::date,
  now() - interval '349 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000028'::uuid,
  'emp28@company.com',
  'Brian',
  'King',
  'employee',
  'Customer Success',
  'Senior Engineer',
  'EMP0028',
  'active',
  (now() - interval '245 days')::date,
  now() - interval '113 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000029'::uuid,
  'emp29@company.com',
  'Ashley',
  'Wright',
  'employee',
  'Sales',
  'Lead',
  'EMP0029',
  'active',
  (now() - interval '670 days')::date,
  now() - interval '338 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000030'::uuid,
  'emp30@company.com',
  'George',
  'Lopez',
  'employee',
  'Sales',
  'Manager',
  'EMP0030',
  'active',
  (now() - interval '670 days')::date,
  now() - interval '617 days',
  now()
) ON CONFLICT (email) DO NOTHING;


-- STEP 2: Create Performance Reviews


INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0001-0000-0000-0000-000000000001'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000078'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.85, 4.73, 4.75,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0002-0000-0000-0000-000000000002'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000099'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.16, 4.12, 4.15,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0003-0000-0000-0000-000000000003'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000027'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.15, 4.19, 4.18,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0004-0000-0000-0000-000000000004'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000026'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.83, 4.87, 4.97,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0005-0000-0000-0000-000000000005'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000079'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.6, 3.62, 3.56,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0006-0000-0000-0000-000000000006'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000068'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.6, 4.53, 4.55,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0007-0000-0000-0000-000000000007'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000039'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.83, 4.01, 3.93,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0008-0000-0000-0000-000000000008'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000015'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.85, 4.82, 4.87,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0009-0000-0000-0000-000000000009'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000049'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  5.0, 4.86, 4.92,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0010-0000-0000-0000-000000000010'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000038'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.95, 4.95, 4.93,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0011-0000-0000-0000-000000000011'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000022'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  5.0, 4.9, 4.96,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0012-0000-0000-0000-000000000012'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000032'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.46, 4.6, 4.57,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0013-0000-0000-0000-000000000013'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000024'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.88, 3.93, 3.98,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0014-0000-0000-0000-000000000014'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000045'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.53, 4.59, 4.66,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0015-0000-0000-0000-000000000015'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000043'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.25, 4.19, 4.14,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0016-0000-0000-0000-000000000016'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000020'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.74, 4.82, 4.72,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0017-0000-0000-0000-000000000017'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000083'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.57, 4.46, 4.51,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0018-0000-0000-0000-000000000018'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000075'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  5.0, 4.81, 4.9,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0019-0000-0000-0000-000000000019'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000048'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.07, 3.95, 4.01,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0020-0000-0000-0000-000000000020'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000059'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.29, 4.12, 4.21,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0021-0000-0000-0000-000000000021'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000009'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.97, 3.96, 3.88,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0022-0000-0000-0000-000000000022'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000074'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.27, 4.34, 4.27,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0023-0000-0000-0000-000000000023'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000060'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  5.0, 4.92, 5.0,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0024-0000-0000-0000-000000000024'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000051'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.74, 3.75, 3.67,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0025-0000-0000-0000-000000000025'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000063'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.24, 4.15, 4.21,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0026-0000-0000-0000-000000000026'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000091'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.19, 4.21, 4.22,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0027-0000-0000-0000-000000000027'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000013'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.87, 4.98, 4.97,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0028-0000-0000-0000-000000000028'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000090'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.51, 4.65, 4.58,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0029-0000-0000-0000-000000000029'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000072'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.94, 3.96, 3.89,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0030-0000-0000-0000-000000000030'::uuid,
  'aaaa0001-0001-0001-0001-000000000001'::uuid,
  'bbbb0000-0000-0000-0000-000000000050'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.71, 3.77, 3.73,
  '2024-01-15'::date + interval '3 days',
  '2024-01-15'::date + interval '5 days',
  '2024-01-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0031-0000-0000-0000-000000000031'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000082'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.74, 4.94, 4.87,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0032-0000-0000-0000-000000000032'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000058'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.63, 3.61, 3.61,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0033-0000-0000-0000-000000000033'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000011'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.24, 4.04, 4.11,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0034-0000-0000-0000-000000000034'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000059'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.54, 4.59, 4.61,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0035-0000-0000-0000-000000000035'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000010'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.71, 4.76, 4.74,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0036-0000-0000-0000-000000000036'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000099'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.43, 3.62, 3.56,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0037-0000-0000-0000-000000000037'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000012'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.83, 4.92, 4.93,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0038-0000-0000-0000-000000000038'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000014'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.8, 4.71, 4.73,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0039-0000-0000-0000-000000000039'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000020'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.55, 4.67, 4.63,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0040-0000-0000-0000-000000000040'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000095'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.16, 4.14, 4.11,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0041-0000-0000-0000-000000000041'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000034'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.75, 4.72, 4.82,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0042-0000-0000-0000-000000000042'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000070'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.45, 4.39, 4.47,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0043-0000-0000-0000-000000000043'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000049'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.97, 4.93, 4.89,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0044-0000-0000-0000-000000000044'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000087'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.39, 3.59, 3.53,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0045-0000-0000-0000-000000000045'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000091'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.74, 4.82, 4.77,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0046-0000-0000-0000-000000000046'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000035'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.17, 4.04, 4.05,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0047-0000-0000-0000-000000000047'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000032'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.73, 3.62, 3.67,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0048-0000-0000-0000-000000000048'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000071'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.79, 4.83, 4.81,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0049-0000-0000-0000-000000000049'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000030'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.39, 4.48, 4.41,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0050-0000-0000-0000-000000000050'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000031'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.4, 4.26, 4.32,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0051-0000-0000-0000-000000000051'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000044'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.13, 4.1, 4.15,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0052-0000-0000-0000-000000000052'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000088'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.9, 4.95, 4.86,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0053-0000-0000-0000-000000000053'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000001'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.66, 3.78, 3.8,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0054-0000-0000-0000-000000000054'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000096'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.5, 4.61, 4.55,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0055-0000-0000-0000-000000000055'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000043'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.01, 4.18, 4.14,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0056-0000-0000-0000-000000000056'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000084'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.8, 4.84, 4.79,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0057-0000-0000-0000-000000000057'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000003'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.4, 4.41, 4.33,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0058-0000-0000-0000-000000000058'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000008'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.55, 4.48, 4.53,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0059-0000-0000-0000-000000000059'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000081'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.66, 3.78, 3.78,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0060-0000-0000-0000-000000000060'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000094'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.78, 4.68, 4.74,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0061-0000-0000-0000-000000000061'::uuid,
  'aaaa0002-0002-0002-0002-000000000002'::uuid,
  'bbbb0000-0000-0000-0000-000000000080'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.2, 4.33, 4.34,
  '2024-04-15'::date + interval '3 days',
  '2024-04-15'::date + interval '5 days',
  '2024-04-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0062-0000-0000-0000-000000000062'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000098'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.84, 3.74, 3.73,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0063-0000-0000-0000-000000000063'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000047'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.2, 4.26, 4.24,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0064-0000-0000-0000-000000000064'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000029'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.45, 4.4, 4.49,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0065-0000-0000-0000-000000000065'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000096'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.85, 4.61, 4.71,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0066-0000-0000-0000-000000000066'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000057'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.91, 4.86, 4.89,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0067-0000-0000-0000-000000000067'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000035'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.69, 4.85, 4.8,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0068-0000-0000-0000-000000000068'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000034'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.26, 4.11, 4.12,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0069-0000-0000-0000-000000000069'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000091'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.62, 3.63, 3.64,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0070-0000-0000-0000-000000000070'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000041'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.46, 4.34, 4.37,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0071-0000-0000-0000-000000000071'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000063'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.61, 3.59, 3.64,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0072-0000-0000-0000-000000000072'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000061'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.0, 3.95, 3.96,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0073-0000-0000-0000-000000000073'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000005'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.39, 4.28, 4.24,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0074-0000-0000-0000-000000000074'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000075'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.06, 4.07, 4.03,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0075-0000-0000-0000-000000000075'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000045'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.73, 4.74, 4.64,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0076-0000-0000-0000-000000000076'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000027'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.6, 3.61, 3.63,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0077-0000-0000-0000-000000000077'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000025'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.64, 3.76, 3.69,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0078-0000-0000-0000-000000000078'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000043'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.83, 4.85, 4.85,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0079-0000-0000-0000-000000000079'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000073'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.51, 3.55, 3.65,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0080-0000-0000-0000-000000000080'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000048'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.15, 4.06, 4.11,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0081-0000-0000-0000-000000000081'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000021'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.77, 3.65, 3.72,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0082-0000-0000-0000-000000000082'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000020'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.59, 4.56, 4.62,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0083-0000-0000-0000-000000000083'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000022'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  5.0, 4.9, 4.94,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0084-0000-0000-0000-000000000084'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000017'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.82, 5.0, 4.95,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0085-0000-0000-0000-000000000085'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000024'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  3.79, 3.86, 3.83,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0086-0000-0000-0000-000000000086'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000086'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.62, 4.59, 4.5,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0087-0000-0000-0000-000000000087'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000080'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.49, 4.41, 4.42,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0088-0000-0000-0000-000000000088'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000033'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.19, 4.36, 4.32,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0089-0000-0000-0000-000000000089'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000093'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.46, 4.35, 4.44,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0090-0000-0000-0000-000000000090'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000015'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.21, 4.07, 4.09,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0091-0000-0000-0000-000000000091'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000042'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.48, 4.45, 4.46,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0092-0000-0000-0000-000000000092'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000064'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.56, 4.7, 4.66,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
) VALUES (
  'cccc0093-0000-0000-0000-000000000093'::uuid,
  'aaaa0003-0003-0003-0003-000000000003'::uuid,
  'bbbb0000-0000-0000-0000-000000000085'::uuid,
  '8bc0f289-c22a-4dba-bbfb-4ac801c11c09'::uuid,
  'submitted', 'submitted', 'completed', 'completed',
  4.48, 4.33, 4.35,
  '2024-07-15'::date + interval '3 days',
  '2024-07-15'::date + interval '5 days',
  '2024-07-15'::date - interval '30 days',
  now()
) ON CONFLICT DO NOTHING;

-- Data generation complete!
-- Total reviews: 93
