
-- ========================================================
-- Comprehensive Performance Review Data Population
-- Generated by populate_performance_data.py
-- ========================================================

-- STEP 1: Create 100 Employee Profiles
-- (This will create profiles that don't already exist)


INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000001'::uuid,
  'emp1@company.com',
  'Sarah',
  'Johnson',
  'employee',
  'Engineering',
  'Senior Software Engineer',
  'EMP0001',
  'active',
  (now() - interval '189 days')::date,
  now() - interval '619 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000002'::uuid,
  'emp2@company.com',
  'Michael',
  'Chen',
  'employee',
  'Engineering',
  'Software Engineer',
  'EMP0002',
  'active',
  (now() - interval '612 days')::date,
  now() - interval '599 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000003'::uuid,
  'emp3@company.com',
  'Emily',
  'Rodriguez',
  'employee',
  'Product',
  'Product Manager',
  'EMP0003',
  'active',
  (now() - interval '317 days')::date,
  now() - interval '460 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000004'::uuid,
  'emp4@company.com',
  'David',
  'Kim',
  'employee',
  'Sales',
  'Account Executive',
  'EMP0004',
  'active',
  (now() - interval '548 days')::date,
  now() - interval '349 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000005'::uuid,
  'emp5@company.com',
  'Jennifer',
  'Martinez',
  'employee',
  'Marketing',
  'Marketing Manager',
  'EMP0005',
  'active',
  (now() - interval '352 days')::date,
  now() - interval '162 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000006'::uuid,
  'emp6@company.com',
  'James',
  'Anderson',
  'employee',
  'Engineering',
  'DevOps Engineer',
  'EMP0006',
  'active',
  (now() - interval '136 days')::date,
  now() - interval '377 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000007'::uuid,
  'emp7@company.com',
  'Maria',
  'Garcia',
  'employee',
  'Customer Success',
  'Customer Success Manager',
  'EMP0007',
  'active',
  (now() - interval '366 days')::date,
  now() - interval '118 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000008'::uuid,
  'emp8@company.com',
  'Robert',
  'Taylor',
  'employee',
  'Finance',
  'Financial Analyst',
  'EMP0008',
  'active',
  (now() - interval '357 days')::date,
  now() - interval '553 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000009'::uuid,
  'emp9@company.com',
  'Linda',
  'Wilson',
  'employee',
  'HR',
  'HR Business Partner',
  'EMP0009',
  'active',
  (now() - interval '436 days')::date,
  now() - interval '446 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000010'::uuid,
  'emp10@company.com',
  'John',
  'Moore',
  'employee',
  'Engineering',
  'Senior Software Engineer',
  'EMP0010',
  'active',
  (now() - interval '622 days')::date,
  now() - interval '225 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000011'::uuid,
  'emp11@company.com',
  'Patricia',
  'Jackson',
  'employee',
  'Customer Success',
  'Coordinator',
  'EMP0011',
  'active',
  (now() - interval '88 days')::date,
  now() - interval '559 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000012'::uuid,
  'emp12@company.com',
  'Christopher',
  'White',
  'employee',
  'Finance',
  'Director',
  'EMP0012',
  'active',
  (now() - interval '458 days')::date,
  now() - interval '479 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000013'::uuid,
  'emp13@company.com',
  'Barbara',
  'Harris',
  'employee',
  'Finance',
  'Coordinator',
  'EMP0013',
  'active',
  (now() - interval '243 days')::date,
  now() - interval '515 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000014'::uuid,
  'emp14@company.com',
  'Daniel',
  'Martin',
  'employee',
  'Operations',
  'Specialist',
  'EMP0014',
  'active',
  (now() - interval '464 days')::date,
  now() - interval '59 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000015'::uuid,
  'emp15@company.com',
  'Nancy',
  'Thompson',
  'employee',
  'HR',
  'Specialist',
  'EMP0015',
  'active',
  (now() - interval '659 days')::date,
  now() - interval '677 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000016'::uuid,
  'emp16@company.com',
  'Matthew',
  'Garcia',
  'employee',
  'Marketing',
  'Manager',
  'EMP0016',
  'active',
  (now() - interval '268 days')::date,
  now() - interval '171 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000017'::uuid,
  'emp17@company.com',
  'Karen',
  'Martinez',
  'employee',
  'Engineering',
  'Specialist',
  'EMP0017',
  'active',
  (now() - interval '212 days')::date,
  now() - interval '501 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000018'::uuid,
  'emp18@company.com',
  'Joseph',
  'Robinson',
  'employee',
  'Product',
  'Director',
  'EMP0018',
  'active',
  (now() - interval '244 days')::date,
  now() - interval '338 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000019'::uuid,
  'emp19@company.com',
  'Susan',
  'Clark',
  'employee',
  'Engineering',
  'Software Engineer',
  'EMP0019',
  'active',
  (now() - interval '447 days')::date,
  now() - interval '605 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000020'::uuid,
  'emp20@company.com',
  'Thomas',
  'Rodriguez',
  'employee',
  'Finance',
  'Lead',
  'EMP0020',
  'active',
  (now() - interval '295 days')::date,
  now() - interval '726 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000021'::uuid,
  'emp21@company.com',
  'Jessica',
  'Lewis',
  'employee',
  'Engineering',
  'Specialist',
  'EMP0021',
  'active',
  (now() - interval '298 days')::date,
  now() - interval '659 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000022'::uuid,
  'emp22@company.com',
  'Charles',
  'Lee',
  'employee',
  'Product',
  'Manager',
  'EMP0022',
  'active',
  (now() - interval '405 days')::date,
  now() - interval '167 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000023'::uuid,
  'emp23@company.com',
  'Sarah',
  'Walker',
  'employee',
  'Operations',
  'Software Engineer',
  'EMP0023',
  'active',
  (now() - interval '107 days')::date,
  now() - interval '663 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000024'::uuid,
  'emp24@company.com',
  'Jason',
  'Hall',
  'employee',
  'Finance',
  'Lead',
  'EMP0024',
  'active',
  (now() - interval '267 days')::date,
  now() - interval '80 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000025'::uuid,
  'emp25@company.com',
  'Lisa',
  'Allen',
  'employee',
  'Customer Success',
  'Manager',
  'EMP0025',
  'active',
  (now() - interval '234 days')::date,
  now() - interval '97 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000026'::uuid,
  'emp26@company.com',
  'Kevin',
  'Young',
  'employee',
  'Sales',
  'Manager',
  'EMP0026',
  'active',
  (now() - interval '422 days')::date,
  now() - interval '129 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000027'::uuid,
  'emp27@company.com',
  'Michelle',
  'Hernandez',
  'employee',
  'Product',
  'Coordinator',
  'EMP0027',
  'active',
  (now() - interval '353 days')::date,
  now() - interval '349 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000028'::uuid,
  'emp28@company.com',
  'Brian',
  'King',
  'employee',
  'Customer Success',
  'Senior Engineer',
  'EMP0028',
  'active',
  (now() - interval '245 days')::date,
  now() - interval '113 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000029'::uuid,
  'emp29@company.com',
  'Ashley',
  'Wright',
  'employee',
  'Sales',
  'Lead',
  'EMP0029',
  'active',
  (now() - interval '670 days')::date,
  now() - interval '338 days',
  now()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO profiles (id, email, first_name, last_name, role, department, job_title, employee_id, status, hire_date, created_at, updated_at)
VALUES (
  'bbbb0000-0000-0000-0000-000000000030'::uuid,
  'emp30@company.com',
  'George',
  'Lopez',
  'employee',
  'Sales',
  'Manager',
  'EMP0030',
  'active',
  (now() - interval '670 days')::date,
  now() - interval '617 days',
  now()
) ON CONFLICT (email) DO NOTHING;


-- STEP 2: Create Performance Reviews


INSERT INTO performance_reviews (
  id, review_cycle_id, employee_id, manager_id,
  self_assessment_status, manager_assessment_status, hr_review_status, overall_status,
  self_overall_rating, manager_overall_rating, final_rating,
  self_assessment_submitted_at, manager_assessment_submitted_at,
  created_at, updated_at
